export const IMAGES = {
  BANNER: {
    TACO_SIGNAL: '/images/banner-1.png',
    NERGET_PLAN: '/images/banner-2.png',
    HOTPLACE: '/images/banner-3.png',
    UPTP: '/images/banner-4.png',
    GUIDE: '/images/banner-5.png',
    TACO_SIGNAL_DESKTOP: '/images/banner-1-desktop.png',
    NERGET_PLAN_DESKTOP: '/images/banner-2-desktop.png',
    HOTPLACE_DESKTOP: '/images/banner-3-desktop.png',
    UPTP_DESKTOP: '/images/banner-4-desktop.png',
    GUIDE_DESKTOP: '/images/banner-5-desktop.png',
  },
  MOONER: {
    'mooner-phone': '/images/mooner-phone.svg',
    'mooner-chat': '/images/mooner-chat.png',
    'moonoz-logo': '/images/moonoz-logo.png',
    'moonoz-hello': '/images/moonoz-hello.png',
    MOONER: '/images/mooner-origin.svg',
    MOONER_GAME: '/images/mooner-game.svg',
    MOONER_PRESENT: '/images/mooner-present.svg',
    MOONER_PENCIL: '/images/mooner-pencil.svg',
    'mooner-hotplace': '/images/mooner-hotplace.png',
    'mooner-share': 'https://d3e0ocbonj571p.cloudfront.net/MoonoZ.png',
    rotation_1: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_1.png',
    rotation_2: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_2.png',
    rotation_3: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_3.png',
    rotation_4: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_4.png',
    'mooner-sad': '/images/mooner-sad.svg',
    'mooner-zone': '/images/moonerzone.png',
  },
  COUPON: {
    TICKET_RED: '/images/ticket-red.svg',
    TICKET_YELLOW: '/images/ticket-yellow.svg',
    TICKET_GRAY: '/images/ticket-gray.svg',
    COUPON_1: '/images/MegaCoffee.png',
    COUPON_2: '/images/BaskinRobbins.png',
    COUPON_3: '/images/Spao.png',
    COUPON_4: '/images/Daiso.png',
    COUPON_5: '/images/Oliveyoung.png',
    COUPON_6: '/images/ParisBaguette.png',
    COUPON_7: '/images/PapaJohns.png',
    COUPON_8: '/images/CU.png',
  },
  TACO: {
    'taco-secret': 'images/taco-secret.png',
    'taco-signal': 'images/taco-signal.png',
    'taco-main-front': 'images/taco-main-front.png',
    'taco-main-back': 'images/taco-main-back.png',
    'taco-pan': 'images/taco-pan.png',
    'taco-sub-back': 'images/taco-sub-back.png',
    'taco-sub-front': 'images/taco-sub-front.png',
    'taco-berry-back': 'images/taco-berry-back.png',
    'taco-berry-front': 'images/taco-berry-front.png',
    'taco-eggy-back': 'images/taco-eggy-back.png',
    'taco-eggy-front': 'images/taco-eggy-front.png',
    'taco-wasab-back': 'images/taco-wasab-back.png',
    'taco-wasab-front': 'images/taco-wasab-front.png',
    'taco-greeny-back': 'images/taco-greeny-back.png',
    'taco-greeny-front': 'images/taco-greeny-front.png',
    'taco-crunch-back': 'images/taco-crunch-back.png',
    'taco-crunch-front': 'images/taco-crunch-front.png',
    'taco-spicy-back': 'images/taco-spicy-back.png',
    'taco-spicy-front': 'images/taco-spicy-front.png',
    'taco-milky-back': 'images/taco-milky-back.png',
    'taco-milky-front': 'images/taco-milky-front.png',
  },
  bubble: '/images/bubble.png',
  PHONE: {
    PHONE_MISSON: '/images/iPhone-mission.png',
    PHONE_MOONOTALK: '/images/iPhone-moonotalk.png',
    PHONE_HOME: '/images/iPhone-home.png',
    PHONE_HOTPLACE: '/images/iPhone-hotplace.png',
    PHONE_MYPAGE: '/images/iPhone-mypage.png',
  },
  yellowBubble: '/images/yellowBubble.png',
} as const;
